version: '3.1'

services:

  db:
    container_name: postgresql
    image: postgres:10.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB : imdb
      PGDATA : /var/lib/postgresql/data
    volumes:
    - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
    - 45432:5432